resources:
  - name: shipit_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/shipit
      branch: master

  - name: shipit_gh_ssh
    type: integration
    integration: avi_gh_ssh

  - name: shipit_dh_cli
    type: cliConfig
    integration: ric03uec-dockerhub

jobs:
  ### Tagging u16 services
  - name: dry_dh_x86_64_Ubuntu_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: u16_img
        switch: off
      - IN: u16_repo
        switch: off
      - IN: u16all_img
        switch: off
      - IN: u16all_repo
        switch: off
      - IN: u16nodall_img
        switch: off
      - IN: u16nodall_repo
        switch: off
      - IN: u16pytall_img
        switch: off
      - IN: u16pytall_repo
        switch: off
      - IN: u16cloall_img
        switch: off
      - IN: u16cloall_repo
        switch: off
      - IN: u16golall_img
        switch: off
      - IN: u16golall_repo
        switch: off
      - IN: u16javall_img
        switch: off
      - IN: u16javall_repo
        switch: off
      - IN: u16scaall_img
        switch: off
      - IN: u16scaall_repo
        switch: off
      - IN: u16ruball_img
        switch: off
      - IN: u16ruball_repo
        switch: off
      - IN: u16phpall_img
        switch: off
      - IN: u16phpall_repo
        switch: off
      - IN: u16cppall_img
        switch: off
      - IN: u16cppall_repo
        switch: off
      - IN: u14_img
        switch: off
      - IN: u14_repo
        switch: off
      - IN: u14all_img
        switch: off
      - IN: u14all_repo
        switch: off
      - IN: u14nodall_img
        switch: off
      - IN: u14nodall_repo
        switch: off
      - IN: u14pytall_img
        switch: off
      - IN: u14pytall_repo
        switch: off
      - IN: u14cloall_img
        switch: off
      - IN: u14cloall_repo
        switch: off
      - IN: u14golall_img
        switch: off
      - IN: u14golall_repo
        switch: off
      - IN: u14javall_img
        switch: off
      - IN: u14javall_repo
        switch: off
      - IN: u14scaall_img
        switch: off
      - IN: u14scaall_repo
        switch: off
      - IN: u14ruball_img
        switch: off
      - IN: u14ruball_repo
        switch: off
      - IN: u14phpall_img
        switch: off
      - IN: u14phpall_repo
        switch: off
      - IN: u14cppall_img
        switch: off
      - IN: u14cppall_repo
        switch: off
      - IN: gitlab_img
        switch: off
      - IN: gitlab_repo
        switch: off
      - IN: postgres_img
        switch: off
      - IN: postgres_repo
        switch: off
      - IN: rabbitmq_img
        switch: off
      - IN: rabbitmq_repo
        switch: off
      - IN: redis_img
        switch: off
      - IN: redis_repo
        switch: off
      - IN: vault_img
        switch: off
      - IN: vault_repo
        switch: off
      - IN: rel_prod
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh drydock dry-dock dhDrydock.txt dry_dh_x86_64_Ubuntu_tag_push
            - popd

  - name: ship_dh_x86_64_Ubuntu_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: microbase_img
        switch: off
      - IN: microbase_repo
        switch: off
      - IN: rel_prod
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh drydock shippable dhShippable.txt dry_dh_x86_64_Ubuntu_tag_push
            - popd

  - name: admiral_Ubuntu_14_04_tag_push
    type: runSh
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: admiral_repo
        switch: off
      - IN: admiral_img
        switch: off
      - IN: rel_prod
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushAdmiralImageRepo.sh admiral_Ubuntu_14_04_tag_push
            - popd

  ### Tagging repo services
  - name: gh_ship_repos_tag_push
    type: runSh
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: execTemplates_repo
        switch: off
      - IN: node_repo
        switch: off
      - IN: cexec_repo
        switch: off
      - IN: reqExec_repo
        switch: off
      - IN: reqProc_repo
        switch: off
      - IN: reqKick_repo
        switch: off
      - IN: rel_prod
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh drydock shippable ghShippable.txt gh_ship_repos_tag_push true
            - popd

  ### Tagging ecr hosted services
  - name: ship_ecr_x86_64_Ubuntu_tag_push
    type: runSh
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipbits_ecr_v2_cli
        scopes:
          - ecr
        switch: off
      - IN: shipit_gh_ssh
        switch: off
#      - IN: mktg_img
#        switch: off
#      - IN: mktg_repo
#        switch: off
      - IN: micro_img
        switch: off
      - IN: micro_repo
        switch: off
#      - IN: nexec_img
#        switch: off
#      - IN: nexec_repo
#        switch: off
#      - IN: api_img
#        switch: off
#      - IN: api_repo
#        switch: off
#      - IN: www_img
#        switch: off
#      - IN: www_repo
#        switch: off
      - IN: rel_prod
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh 374168611083.dkr.ecr.us-east-1.amazonaws.com shippable ecrShippable.txt ship_ecr_x86_64_Ubuntu_tag_push
            - popd