resources:
  - name: shipit_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/shipit
      branch: master

  - name: shipit_gh_ssh
    type: integration
    integration: avi_gh_ssh

  - name: shipit_dh_cli
    type: cliConfig
    integration: ric03uec-dockerhub

jobs:
  ### Tagging u16 services
  - name: dry_dh_x86_64_Ubuntu_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: u16_img
        switch: off
      - IN: u16_repo
        switch: off
      - IN: u16all_img
        switch: off
      - IN: u16all_repo
        switch: off
      - IN: u16nodall_img
        switch: off
      - IN: u16nodall_repo
        switch: off
      - IN: u16pytall_img
        switch: off
      - IN: u16pytall_repo
        switch: off
      - IN: u16cloall_img
        switch: off
      - IN: u16cloall_repo
        switch: off
      - IN: u16golall_img
        switch: off
      - IN: u16golall_repo
        switch: off
      - IN: u16javall_img
        switch: off
      - IN: u16javall_repo
        switch: off
      - IN: u16scaall_img
        switch: off
      - IN: u16scaall_repo
        switch: off
      - IN: u16ruball_img
        switch: off
      - IN: u16ruball_repo
        switch: off
      - IN: u16phpall_img
        switch: off
      - IN: u16phpall_repo
        switch: off
      - IN: u16cppall_img
        switch: off
      - IN: u16cppall_repo
        switch: off
      - IN: rel_prod
      - TASK:
        - script: |
            pushd $(shipctl get_resource_state "shipit_repo")
              ./tagAndPushSvcs.sh drydock dry-dock dhDrydock.txt shipit_repo
            popd