resources:
  - name: shipit_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/shipit
      branch: master

  - name: reqKick_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/reqKick
      branch: master

  - name: reqProc_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/reqProc
      branch: master

  - name: reqExec_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/reqExec
      branch: master

  - name: execTemplates_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/execTemplates
      branch: master

  - name: shipit_gh_ssh
    type: integration
    integration: avi_gh_ssh

  - name: shipit_dh_cli
    type: cliConfig
    integration: ric03uec-dockerhub

  - name: shipit_bits_cli
    type: cliConfig
    integration: ecr_bits_push
    pointer:
      region: us-east-1

  - name: shipit_bits_access_cli
    type: cliConfig
    integration: aws_bits_access
    pointer:
      region: us-east-1

  - name: shipit_rc_pem
    type: integration
    integration: aws-rc-pem

  - name: shipit_rc_swarm
    type: params
    version:
      params:
        secure: vmR5kHmceqFIKNoMgcx4cxCTQptaJ29V+YEQXqjVQ9gAMLzBxeSoO9+/ZPUgbO33sp291HG0k8Qrx/gbaKEGM6UufX9TTmlL8Yw/XahKjfx3ZWf2uKvNGN8aqBue2g8A/HSC0f9vt4Zf1oacRsrXof/9L5HWcKfoD5GJjezTHnpqHjWuYB0lz7ApzSKpGLi0n2yycjNTMPycwO5l0BCRGkNBj82ak3cUM98omN6+bB9cACTGvbcFgufaBFfa35SCtEDUZpn7OoZhk+T+1YmjP3EK+mgcEerA1zG7avSfFCQmBqI5M7xBoVG+CAQ4gF7RVXjxCpFseaBVS8jcvEC8CQ==

  - name: shippable_version
    type: version
    seed:
      versionName: "6.1.0"

jobs:
  ### Tagging u16 services
  - name: dry_dh_x86_64_Ubuntu_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: u16_img
        switch: off
      - IN: u16_repo
        switch: off
      - IN: u16all_img
        switch: off
      - IN: u16all_repo
        switch: off
      - IN: u16nodall_img
        switch: off
      - IN: u16nodall_repo
        switch: off
      - IN: u16pytall_img
        switch: off
      - IN: u16pytall_repo
        switch: off
      - IN: u16cloall_img
        switch: off
      - IN: u16cloall_repo
        switch: off
      - IN: u16golall_img
        switch: off
      - IN: u16golall_repo
        switch: off
      - IN: u16javall_img
        switch: off
      - IN: u16javall_repo
        switch: off
      - IN: u16scaall_img
        switch: off
      - IN: u16scaall_repo
        switch: off
      - IN: u16ruball_img
        switch: off
      - IN: u16ruball_repo
        switch: off
      - IN: u16phpall_img
        switch: off
      - IN: u16phpall_repo
        switch: off
      - IN: u16cppall_img
        switch: off
      - IN: u16cppall_repo
        switch: off
      - IN: u14_img
        switch: off
      - IN: u14_repo
        switch: off
      - IN: u14all_img
        switch: off
      - IN: u14all_repo
        switch: off
      - IN: u14nodall_img
        switch: off
      - IN: u14nodall_repo
        switch: off
      - IN: u14pytall_img
        switch: off
      - IN: u14pytall_repo
        switch: off
      - IN: u14cloall_img
        switch: off
      - IN: u14cloall_repo
        switch: off
      - IN: u14golall_img
        switch: off
      - IN: u14golall_repo
        switch: off
      - IN: u14javall_img
        switch: off
      - IN: u14javall_repo
        switch: off
      - IN: u14scaall_img
        switch: off
      - IN: u14scaall_repo
        switch: off
      - IN: u14ruball_img
        switch: off
      - IN: u14ruball_repo
        switch: off
      - IN: u14phpall_img
        switch: off
      - IN: u14phpall_repo
        switch: off
      - IN: u14cppall_img
        switch: off
      - IN: u14cppall_repo
        switch: off
      - IN: gitlab_img
        switch: off
      - IN: gitlab_repo
        switch: off
      - IN: postgres_img
        switch: off
      - IN: postgres_repo
        switch: off
      - IN: rabbitmq_img
        switch: off
      - IN: rabbitmq_repo
        switch: off
      - IN: redis_img
        switch: off
      - IN: redis_repo
        switch: off
      - IN: vault_img
        switch: off
      - IN: vault_repo
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh drydock dry-dock dhDrydock.txt dry_dh_x86_64_Ubuntu_tag_push
            - popd

  - name: ship_dh_x86_64_Ubuntu_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: microbase_img
        switch: off
      - IN: microbase_repo
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh drydock shippable dhShippable.txt dry_dh_x86_64_Ubuntu_tag_push
            - popd

  - name: admiral_Ubuntu_14_04_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: admiral_repo
        switch: off
      - IN: admiral_img
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushAdmiralImageRepo.sh admiral_Ubuntu_14_04_tag_push
            - popd

  ### Tagging repo services
  - name: gh_ship_repos_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: execTemplates_repo
        switch: off
      - IN: node_repo
        switch: off
      - IN: cexec_repo
        switch: off
      - IN: reqExec_repo
        switch: off
      - IN: reqProc_repo
        switch: off
      - IN: reqKick_repo
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh drydock shippable ghShippable.txt gh_ship_repos_tag_push true
            - popd

  ### Tagging ecr hosted services
  - name: ship_ecr_x86_64_Ubuntu_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_bits_cli
        scopes:
          - ecr
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: mktg_img
        switch: off
      - IN: mktg_repo
        switch: off
      - IN: micro_img
        switch: off
      - IN: micro_repo
        switch: off
      - IN: nexec_img
        switch: off
      - IN: nexec_repo
        switch: off
      - IN: api_img
        switch: off
      - IN: api_repo
        switch: off
      - IN: www_img
        switch: off
      - IN: www_repo
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh 374168611083.dkr.ecr.us-east-1.amazonaws.com shippable ecrShippable.txt ship_ecr_x86_64_Ubuntu_tag_push
            - popd

  - name: genexec_tag_push
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: shipit_repo
        switch: off
      - IN: genexec_img
        switch: off
      - IN: shipit_bits_cli
        scopes:
          - ecr
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushImage.sh genexec 374168611083.dkr.ecr.us-east-1.amazonaws.com prod_release
            - ./tagAndPushImage.sh genexec drydock prod_release
            - popd

  - name: reqProc_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushImage.sh reqproc drydock prod_release
            - ./tagAndPushImage.sh m10reqproc drydock prod_release
            - echo "This should run ./IN/config_repo/gitRepo/tagAndPushImage.sh w16reqproc drydock"
            - ./tagAndPushImage.sh reqproc drydockaarch64 prod_release
            - popd

  - name: reqExec_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_bits_access_cli
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagReqExecArtifacts.sh x86_64 Ubuntu_16.04 prod_release
            - ./tagReqExecArtifacts.sh x86_64 Ubuntu_14.04 prod_release
            - ./tagReqExecArtifacts.sh x86_64 CentOS_7 prod_release
            - ./tagReqExecArtifacts.sh x86_64 macOS_10.12 prod_release
            - echo "This should run ./IN/config_repo/gitRepo/tagReqExecArtifacts.sh x86_64 WindowsServer_2016 prod_release"
            - ./tagReqExecArtifacts.sh aarch64 Ubuntu_16.04 prod_release
            - popd

  - name: dry_dh_aarch_64_Ubuntu_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: aarch64_microbase_img
        switch: off
      - IN: aarch64_microbase_repo
        switch: off
      - IN: aarch64_u16_img
        switch: off
      - IN: aarch64_u16_repo
        switch: off
      - IN: aarch64_u16pyt_img
        switch: off
      - IN: aarch64_u16pyt_repo
        switch: off
      - IN: aarch64_u16cpp_img
        switch: off
      - IN: aarch64_u16cpp_repo
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh drydockaarch64 dry-dock-aarch64 dhAarch64.txt dry_dh_aarch_64_Ubuntu_tag_push
            - popd

  - name: mktg_patch
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_bits_cli
        scopes:
          - ecr
        switch: off
      - IN: mktg_img
        switch: off
      - IN: prod_release
        switch: off
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./patchImage.sh mktg 374168611083.dkr.ecr.us-east-1.amazonaws.com prod_release
            - popd

  - name: rc_deploy
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    on_start:
      - NOTIFY: slack_rc
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_rc_pem
        switch: off
      - IN: shipit_rc_swarm
        switch: off
      - IN: baseami_patch
      - IN: api_img
      - IN: www_img
      - IN: nexec_img
      - IN: mktg_img
      - IN: micro_img
      - IN: admiral_img
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./deployRc.sh
            - popd
    on_success:
      - NOTIFY: slack_rc
    on_failure:
      - NOTIFY: slack_rc

  - name: prod_release
    type: release
    steps:
      - IN: shippable_version
        switch: off
      - IN: rc_deploy
        switch: off
      - TASK: managed
        bump: patch
