resources:
  - name: shipit_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/shipit
      branch: master

  - name: reqKick_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/reqKick
      branch: master

  - name: reqProc_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/reqProc
      branch: master

  - name: execTemplates_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/execTemplates
      branch: master

  - name: shipit_gh_ssh
    type: integration
    integration: avi_gh_ssh

  - name: shipit_dh_cli
    type: cliConfig
    integration: ric03uec-dockerhub

  - name: shipit_bits_cli
    type: cliConfig
    integration: ecr_bits_push
    pointer:
      region: us-east-1

  - name: shipit_bits_access_cli
    type: cliConfig
    integration: aws_bits_access
    pointer:
      region: us-east-1

  - name: shipit_rc_pem
    type: integration
    integration: aws-rc-pem

  - name: shipit_rc_swarm
    type: params
    version:
      params:
        secure: YFz2Vp+Rs5wa2oqAqfcZQsQQJjYrJkjr5oqJwC9B+guuckJ7zww575VD+5HgDxpNQ8q3IAvLHMBABaDl4m7XDdDvge+z9pgLC/TIiMIAl8LxzEJ3C+H/iF5JWS85O9iMc5000484KMEFZ10fmdijr7QkynaPntGerAbcKECP3X3d1PNDHTaJrJbq8gJqSlc6GT12fmscFMcZRP3vkuBK5ZeSr18PwL+zjqLLbPa2CPSQmMwHDIC6EgfW2va8SAH0eMml+cQ5U4ualbOTj2SExxdkXyJ1bm37WGS4zY1WIydFqGhLNQITq0NiYKNHbEXmGp5rlLivhFmZimd+WDOP7Q==
  - name: shippable_version
    type: version
    seed:
      versionName: "6.4.3"

  - name: rc_slack
    type: notification
    integration: ship-slack
    pointer:
      recipients:
        - "#rc"

  - name: prod_slack
    type: notification
    integration: ship-slack
    pointer:
      recipients:
        - "#prod"

jobs:
  ### Tagging c7 services
  - name: dry_dh_x86_64_c7_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: c7_dd_repo
        switch: off
      - IN: c7all_dd_repo
        switch: off
      - IN: c7nodall_dd_repo
        switch: off
      - IN: c7pytall_dd_repo
        switch: off
      - IN: c7javall_dd_repo
        switch: off
      - IN: c7cppall_dd_repo
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh drydock dry-dock dhc7Drydock.txt dry_dh_x86_64_c7_tag_push
            - popd
  ### Tagging u16 services
  - name: dry_dh_x86_64_u16_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: u16_dd_repo
        switch: off
      - IN: u16all_dd_repo
        switch: off
      - IN: u16nodall_dd_repo
        switch: off
      - IN: u16pytall_dd_repo
        switch: off
      - IN: u16cloall_dd_repo
        switch: off
      - IN: u16golall_dd_repo
        switch: off
      - IN: u16javall_dd_repo
        switch: off
      - IN: u16scaall_dd_repo
        switch: off
      - IN: u16ruball_dd_repo
        switch: off
      - IN: u16phpall_dd_repo
        switch: off
      - IN: u16cppall_dd_repo
        switch: off
      - IN: u16microbase_dd_repo
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh drydock dry-dock dhu16Drydock.txt dry_dh_x86_64_u16_tag_push
            - popd

  ### Tagging u14 services
  - name: dry_dh_x86_64_Ubuntu_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: u14_dd_repo
        switch: off
      - IN: u14all_dd_repo
        switch: off
      - IN: u14nodall_dd_repo
        switch: off
      - IN: u14pytall_dd_repo
        switch: off
      - IN: u14cloall_dd_repo
        switch: off
      - IN: u14golall_dd_repo
        switch: off
      - IN: u14javall_dd_repo
        switch: off
      - IN: u14scaall_dd_repo
        switch: off
      - IN: u14ruball_dd_repo
        switch: off
      - IN: u14phpall_dd_repo
        switch: off
      - IN: u14cppall_dd_repo
        switch: off
      - IN: u14microbase_dd_repo
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh drydock dry-dock dhu14Drydock.txt dry_dh_x86_64_Ubuntu_tag_push
            - popd

  - name: dry_dh_aarch_64_Ubuntu_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      architecture: aarch64
      os: Ubuntu_16.04
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: u16microbase_dd_repo
        switch: off
      - IN: u16_aarch64_dd_repo
        switch: off
      - IN: u16all_aarch64_dd_repo
        switch: off
      - IN: u16nodall_aarch64_dd_repo
        switch: off
      - IN: u16cppall_aarch64_dd_repo
        switch: off
      - IN: u16pytall_aarch64_dd_repo
        switch: off
      - IN: u16javall_aarch64_dd_repo
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh drydock dry-dock dhAarch64.txt dry_dh_aarch_64_Ubuntu_tag_push
            - popd

  - name: dry_dh_aarch32_Ubuntu_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: aarch32_u16_img
        switch: off
      - IN: aarch32_u16_repo
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh drydock dry-dock dhAarch32.txt dry_dh_aarch32_Ubuntu_tag_push
            - popd

  - name: dry_dh_x86_64_Windows_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_w16_cus_01
      container: false
    steps:
    - IN: shipit_repo
      switch: off
    - IN: shipit_dh_cli
      switch: off
    - IN: shipit_gh_ssh
      switch: off
    - IN: w16_repo
      switch: off
    - IN: w16dotnetcore_repo
      switch: off
    - IN: w16aspnetcore_repo
      switch: off
    - IN: prod_release
    - TASK:
        script:
          - pushd $(shipctl get_resource_state "shipit_repo")
          - ./tagAndPushSvcs.ps1 drydock dry-dock dhDrydockWindows.txt dry_dh_x86_64_Windows_tag_push
          - popd

  - name: tag_admiral_repo
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: u16admiral_sh_repo
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAdmiralRepo.sh tag_admiral_repo
            - popd

  - name: tag_push_admiral_images
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: tag_admiral_repo
      - IN: shipit_repo
        switch: off
      - IN: shipit_bits_cli
        scopes:
          - ecr
        switch: off
      - IN: u14admiral_sh_img
        switch: off
      - IN: u16admiral_sh_img
        switch: off
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagPushAdmiralImages.sh tag_push_admiral_images u14admiral u16admiral
            - popd

  ### Tagging repo services
  - name: gh_ship_repos_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: execTemplates_repo
        switch: off
      - IN: node_repo
        switch: off
      - IN: cexec_repo
        switch: off
      - IN: reqExec_repo
        switch: off
      - IN: reqProc_repo
        switch: off
      - IN: reqKick_repo
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh drydock shippable ghShippable.txt gh_ship_repos_tag_push true
            - popd

  ### Tagging ecr hosted services
  - name: ship_ecr_x86_64_Ubuntu_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_bits_cli
        scopes:
          - ecr
        switch: off
      - IN: shipit_gh_ssh
        switch: off
      - IN: mktg_sh_img
        switch: off
      - IN: mktg_sh_repo
        switch: off
      - IN: micro_sh_img
        switch: off
      - IN: micro_sh_repo
        switch: off
      - IN: nexec_sh_img
        switch: off
      - IN: nexec_sh_repo
        switch: off
      - IN: api_sh_img
        switch: off
      - IN: api_sh_repo
        switch: off
      - IN: www_sh_img
        switch: off
      - IN: www_sh_repo
        switch: off
      - IN: postgres_img
        switch: off
      - IN: postgres_repo
        switch: off
      - IN: gitlab_img
        switch: off
      - IN: gitlab_repo
        switch: off
      - IN: rabbitmq_img
        switch: off
      - IN: rabbitmq_repo
        switch: off
      - IN: redis_img
        switch: off
      - IN: redis_repo
        switch: off
      - IN: vault_img
        switch: off
      - IN: vault_repo
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushSvcs.sh 374168611083.dkr.ecr.us-east-1.amazonaws.com shippable ecrShippable.txt ship_ecr_x86_64_Ubuntu_tag_push
            - ./tagAndPushSvcs.sh 374168611083.dkr.ecr.us-east-1.amazonaws.com dry-dock ecrDrydock.txt ship_ecr_x86_64_Ubuntu_tag_push
            - popd

  - name: genexec_tag_push
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: shipit_repo
        switch: off
      - IN: genexec_sh_img
        switch: off
      - IN: shipit_bits_cli
        scopes:
          - ecr
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushImage.sh genexec 374168611083.dkr.ecr.us-east-1.amazonaws.com prod_release
            - ./tagAndPushImage.sh genexec drydock prod_release
            - popd

  - name: reqProc_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushImage.sh u16reqproc drydock prod_release
            - ./tagAndPushImage.sh u14reqproc drydock prod_release
            - ./tagAndPushImage.sh m10reqproc drydock prod_release
            - ./tagAndPushImage.sh aarch64_u16reqproc drydock prod_release
            - popd

  - name: reqProc_tag_push_w16
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_w16_cus_01
      container: false
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_dh_cli
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - .\tagAndPushImage.ps1 w16reqproc drydock prod_release
            - popd

  - name: reqExec_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_bits_access_cli
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagReqExecArtifacts.sh x86_64 Ubuntu_16.04 prod_release "tar.gz"
            - ./tagReqExecArtifacts.sh x86_64 Ubuntu_14.04 prod_release "tar.gz"
            - ./tagReqExecArtifacts.sh x86_64 CentOS_7 prod_release "tar.gz"
            - ./tagReqExecArtifacts.sh x86_64 macOS_10.12 prod_release "tar.gz"
            - ./tagReqExecArtifacts.sh x86_64 WindowsServer_2016 prod_release zip
            - ./tagReqExecArtifacts.sh aarch64 Ubuntu_16.04 prod_release "tar.gz"
            - popd

  - name: reports_tag_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_bits_access_cli
        switch: off
      - IN: prod_release
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagReportsArtifacts.sh x86_64 Ubuntu_16.04 prod_release "tar.gz"
            - ./tagReportsArtifacts.sh x86_64 Ubuntu_14.04 prod_release "tar.gz"
            - ./tagReportsArtifacts.sh x86_64 CentOS_7 prod_release "tar.gz"
            - ./tagReportsArtifacts.sh aarch64 Ubuntu_16.04 prod_release "tar.gz"
            - popd

  - name: ship_s3_repo_archives_push
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_bits_access_cli
        switch: off
      - IN: tag_push_admiral_images
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./tagAndPushArchives.sh "s3Shippable.txt" "tar.gz"
            - popd

  - name: mktg_patch
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_bits_cli
        scopes:
          - ecr
        switch: off
      - IN: mktg_sh_img
        switch: off
      - IN: prod_release
        switch: off
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./patchImage.sh mktg 374168611083.dkr.ecr.us-east-1.amazonaws.com prod_release
            - popd

  - name: rc_deploy
    type: runSh
    dependencyMode: strict
    runtime:
      timeoutMinutes: 15
    on_start:
      - NOTIFY: rc_slack
    steps:
      - IN: shipit_repo
        switch: off
      - IN: shipit_rc_pem
        switch: off
      - IN: shipit_rc_swarm
        switch: off
      - IN: baseami_patch
      - IN: api_sh_img
      - IN: www_sh_img
      - IN: nexec_sh_img
      - IN: mktg_sh_img
      - IN: micro_sh_img
      - IN: u16admiral_sh_img
      - IN: shipit_bits_cli
        scopes:
          - ecr
        switch: off
      - TASK:
          name: deploy_to_rc
          script:
            - pushd $(shipctl get_resource_state "shipit_repo")
            - ./deployRc.sh
            - popd
      - TASK:
          name: cleanup_untagged_images
          script:
            - |
              repositories=$(aws ecr describe-repositories --output text | awk '{print $5}')
              while read -r repo; do
                untagged_images=$(aws ecr list-images --repository-name $repo --filter tagStatus=UNTAGGED --query 'imageIds[*]' --output text)
                while read -r untagged_image; do
                  if [ ! -z "$untagged_image" ]; then
                    echo "Deleting untagged image: $untagged_image from repo: $repo"
                    aws ecr batch-delete-image --repository-name $repo --image-ids imageDigest="$untagged_image"
                  else
                    echo "No untagged image present in repo: $repo"
                  fi
                done <<< "$untagged_images"
              done <<< "$repositories"
    on_success:
      - NOTIFY: rc_slack
    on_failure:
      - NOTIFY: rc_slack

  - name: prod_release
    type: release
    steps:
      - IN: shippable_version
        switch: off
      - IN: bvt
        switch: off
      - TASK: managed
        bump: patch
