resources:
  - name: u16microbase_dd_repo
    type: gitRepo
    integration: avinci_gh
    versionTemplate:
      sourceName: dry-dock/u16microbase
      branch: master

  - name: u16microbase_dd_img
    type: image
    integration: shipDH
    versionTemplate:
      sourceName: "drydock/u16microbase"
      versionName: master

jobs:
  - name: u16microbase_x8664_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: u16microbase_dd_repo
      - TASK:
          name: u16microbase_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "u16microbase_dd_img"
                - RES_REPO: "u16microbase_dd_repo"
          script:
            - pushd $(shipctl get_resource_state "$RES_REPO")
            - REPO_COMMIT=$(shipctl get_resource_version_key "$RES_REPO" "shaData.commitSha")
            - export IMG_NAME=$(shipctl get_resource_version_key $IMG_OUT "sourceName")
            - export DH_USR_NAME=$(shipctl get_integration_resource_field $IMG_OUT "userName")
            - export DH_PASS=$(shipctl get_integration_resource_field $IMG_OUT "password")
            - sudo docker build -t=$IMG_NAME:$REL_VER --pull .
            - sudo docker login -u $DH_USR_NAME -p $DH_PASS
            - sudo docker push $IMG_NAME:$REL_VER
      - OUT: u16microbase_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi $IMG_OUT "versionName=$REL_VER" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER"
